import 'package:shared_preferences/shared_preferences.dart';
import 'dart:ui' as ui;

class LanguageManager {
  static const String _languageKey = 'selected_language';
  static const String _defaultLanguage = 'Türkçe';
  
  // Desteklenen diller ve kodları
  static const Map<String, String> _supportedLanguages = {
    'en': 'English',
    'tr': 'Türkçe',
    'ar': 'العربية',
  };
  
  static final Map<String, Map<String, String>> _translations = {
    'Türkçe': {
      // Ana Sayfa
      'Ana Sayfa': 'Ana Sayfa',
      'Hoş Geldiniz': 'Hoş Geldiniz',
      'Ürün ara...': 'Ürün ara...',
      'Tümü': 'Tümü',
      'Kıyafet': 'Kıyafet',
      'Elektronik': 'Elektronik',
      'Kozmetik': 'Kozmetik',
      'Mobilya': 'Mobilya',
      'Spor': 'Spor',
      'Oyuncak': 'Oyuncak',
      'Ürün bulunamadı': 'Ürün bulunamadı',
      'Keşfet': 'Keşfet',
      
      // Sepet
      'Sepetim': 'Sepetim',
      'Ürünleriniz': 'Ürünleriniz',
      'Seçim Yap': 'Seçim Yap',
      'Toplam:': 'Toplam:',
      'Ödemeye Geç': 'Ödemeye Geç',
      'Ürün Sepette': 'Ürün Sepette',
      'Sepete Ekle': 'Sepete Ekle',
      'Sepetiniz boş': 'Sepetiniz boş',
      'Giriş Gerekli': 'Giriş Gerekli',
      'Ödeme işlemi için giriş yapmanız gerekiyor!': 'Ödeme işlemi için giriş yapmanız gerekiyor!',
      
      // Profil
      'Profilim': 'Profilim',
      'Hesap Bilgileriniz': 'Hesap Bilgileriniz',
      'Hesap Bilgileri': 'Hesap Bilgileri',
      'Siparişlerim': 'Siparişlerim',
      'Favorilerim': 'Favorilerim',
      'Adreslerim': 'Adreslerim',
      'Ödeme Yöntemleri': 'Ödeme Yöntemleri',
      'Ayarlar': 'Ayarlar',
      'Çıkış Yap': 'Çıkış Yap',
      'Takip Ettiğim Satıcılar': 'Takip Ettiğim Satıcılar',

      // Ürün Detayı
      'Ürün Detayı': 'Ürün Detayı',
      'Ürün Açıklaması': 'Ürün Açıklaması',
      'Satıcı Bilgileri': 'Satıcı Bilgileri',
      
      // Ayarlar
      'Genel Ayarlar': 'Genel Ayarlar',
      'Dil': 'Dil',
      'Dil Seçimi': 'Dil Seçimi',
      'İptal': 'İptal',
      'Uygulama Hakkında': 'Uygulama Hakkında',
      'Versiyon': 'Versiyon',
      'Gizlilik Politikası': 'Gizlilik Politikası',
      'Kullanım Şartları': 'Kullanım Şartları',
      
      // Giriş/Kayıt
      'Giriş Yap': 'Giriş Yap',
      'Kayıt Ol': 'Kayıt Ol',
      'E-posta': 'E-posta',
      'Şifre': 'Şifre',
      'Şifremi Unuttum': 'Şifremi Unuttum',
      'Giriş Yap/Kayıt Ol': 'Giriş Yap/Kayıt Ol',
      'E-posta adresiniz': 'E-posta adresiniz',
      'Şifreniz': 'Şifreniz',
      'Geçerli bir e-posta adresi giriniz': 'Geçerli bir e-posta adresi giriniz',
      'Şifre en az 6 karakter olmalıdır': 'Şifre en az 6 karakter olmalıdır',
      'Lütfen tüm alanları doldurunuz!': 'Lütfen tüm alanları doldurunuz!',
      'E-posta veya şifre hatalı!': 'E-posta veya şifre hatalı!',
      'Giriş Başarısız': 'Giriş Başarısız',
      'Hesabınız yok mu?': 'Hesabınız yok mu?',
      'Kayıt Olun': 'Kayıt Olun',
      'Hesabınıza giriş yapın': 'Hesabınıza giriş yapın',
      'Hata': 'Hata',
      'Bilgi': 'Bilgi',
      'Tamam': 'Tamam',
      'Hesap Oluştur': 'Hesap Oluştur',
      'Bilgilerinizi girerek hesap oluşturun': 'Bilgilerinizi girerek hesap oluşturun',
      'Ad Soyad': 'Ad Soyad',
      'Ad soyad en az 2 karakter olmalıdır': 'Ad soyad en az 2 karakter olmalıdır',
      'Telefon': 'Telefon',
      'Geçerli bir telefon numarası giriniz': 'Geçerli bir telefon numarası giriniz',
      'Şifre Tekrar': 'Şifre Tekrar',
      'Şifreler eşleşmiyor': 'Şifreler eşleşmiyor',
      'Kayıt Başarılı': 'Kayıt Başarılı',
      'Hesabınız başarıyla oluşturuldu!': 'Hesabınız başarıyla oluşturuldu!',
      'Zaten hesabınız var mı?': 'Zaten hesabınız var mı?',
      'Giriş Yapın': 'Giriş Yapın',
      
      // Ödeme Sayfası
      'Ödeme': 'Ödeme',
      'Teslimat Adresi': 'Teslimat Adresi',
      'Kayıtlı adres yok. Lütfen profilinizden adres ekleyin.': 'Kayıtlı adres yok. Lütfen profilinizden adres ekleyin.',
      'Adres': 'Adres',
      'Ödeme Kartı': 'Ödeme Kartı',
      'Kayıtlı kart yok. Lütfen profilinizden kart ekleyin.': 'Kayıtlı kart yok. Lütfen profilinizden kart ekleyin.',
      'CVV': 'CVV',
      'Sepet Özeti': 'Sepet Özeti',
      'Ödemeyi Tamamla': 'Ödemeyi Tamamla',
      'Lütfen adres ve kart seçiniz!': 'Lütfen adres ve kart seçiniz!',
      'CVV 3 haneli olmalı!': 'CVV 3 haneli olmalı!',
      'CVV hatalı!': 'CVV hatalı!',
      'Kart bakiyesi yetersiz!': 'Kart bakiyesi yetersiz!',
      'Ödeme Başarısız': 'Ödeme Başarısız',
      'Ödeme işlemi başarısız:': 'Ödeme işlemi başarısız:',
      'Para çekilmedi!': 'Para çekilmedi!',
      
      // Satıcı
      'Satıcı Ol': 'Satıcı Ol',
      'Satıcı Paneli': 'Satıcı Paneli',
      
      // Navigasyon
      'Sepet': 'Sepet',
      'Profil': 'Profil',
      
      // Ödeme Başarılı Sayfası
      'Ödeme Başarılı!': 'Ödeme Başarılı!',
      'Siparişiniz başarıyla alındı.': 'Siparişiniz başarıyla alındı.',
      'Ana Sayfaya Dön': 'Ana Sayfaya Dön',
      
      // Şifre Sıfırlama
      'Şifre Sıfırlama': 'Şifre Sıfırlama',
      'Bilgilerinizi girerek şifrenizi sıfırlayın': 'Bilgilerinizi girerek şifrenizi sıfırlayın',
      'Yeni Şifre': 'Yeni Şifre',
      'Şifreyi Sıfırla': 'Şifreyi Sıfırla',
      'Telefon numarası 11 haneli olmalıdır': 'Telefon numarası 11 haneli olmalıdır',
      'Şifre en az 8 karakter, bir büyük harf, bir küçük harf ve bir rakam içermelidir': 'Şifre en az 8 karakter, bir büyük harf, bir küçük harf ve bir rakam içermelidir',
      'Form Hatası': 'Form Hatası',
      'Lütfen tüm alanları doğru şekilde doldurunuz!': 'Lütfen tüm alanları doğru şekilde doldurunuz!',
      'Geçerli bir e-posta adresi giriniz!': 'Geçerli bir e-posta adresi giriniz!',
      'Şifre en az 8 karakter, bir büyük harf, bir küçük harf ve bir rakam içermelidir!': 'Şifre en az 8 karakter, bir büyük harf, bir küçük harf ve bir rakam içermelidir!',
      'Telefon numarası 11 haneli olmalıdır!': 'Telefon numarası 11 haneli olmalıdır!',
      'Bu telefon numarasına kayıtlı başka bir hesap vardır': 'Bu telefon numarasına kayıtlı başka bir hesap vardır',
      'Bu telefon numarası zaten doğrulanmış': 'Bu telefon numarası zaten doğrulanmış',
      'Başarılı!': 'Başarılı!',
      'Şifreniz başarıyla değiştirildi. Yeni şifrenizle giriş yapabilirsiniz.': 'Şifreniz başarıyla değiştirildi. Yeni şifrenizle giriş yapabilirsiniz.',
      'Bilgiler eşleşmiyor! Lütfen girdiğiniz bilgileri kontrol edin.': 'Bilgiler eşleşmiyor! Lütfen girdiğiniz bilgileri kontrol edin.',
      'Şifre değiştirme sırasında bir hata oluştu. Lütfen tekrar deneyin.': 'Şifre değiştirme sırasında bir hata oluştu. Lütfen tekrar deneyin.',
      'Geri dönmek istiyor musunuz? ': 'Geri dönmek istiyor musunuz? ',
      'Şifreyi Güncelle': 'Şifreyi Güncelle',
      'Şifrenizi değiştirdikten sonra yeniden giriş yapmanız gerekir.': 'Şifrenizi değiştirdikten sonra yeniden giriş yapmanız gerekir.',
      
      // Kayıt Ol Sayfası
      'Kayıt Başarısız': 'Kayıt Başarısız',
      'Bu telefon numarası zaten kullanımda olabilir. Lütfen farklı bir telefon numarası deneyin.': 'Bu telefon numarası zaten kullanımda olabilir. Lütfen farklı bir telefon numarası deneyin.',
      'Email Doğrulama': 'Email Doğrulama',
      'Email doğrulanmış': 'Email doğrulanmış',
      'Email doğrulanmamış': 'Email doğrulanmamış',
      'Doğrulama Kodu Gönder': 'Doğrulama Kodu Gönder',
      'Gönderiliyor...': 'Gönderiliyor...',
      'Doğrulama kodu': 'Doğrulama kodu',
      'Doğrula': 'Doğrula',
      'Email doğrulama kodu gönderildi!': 'Email doğrulama kodu gönderildi!',
      'Email adresi başarıyla doğrulandı!': 'Email adresi başarıyla doğrulandı!',
      'Lütfen doğrulama kodunu girin!': 'Lütfen doğrulama kodunu girin!',
      'Telefon Doğrulama': 'Telefon Doğrulama',
      'Telefon doğrulanmış': 'Telefon doğrulanmış',
      'Telefon doğrulanmamış': 'Telefon doğrulanmamış',
      'Telefonu Doğrula': 'Telefonu Doğrula',
      'Hesabınız başarıyla oluşturuldu. Şimdi giriş yapabilirsiniz.': 'Hesabınız başarıyla oluşturuldu. Şimdi giriş yapabilirsiniz.',
      'Kod Gönder': 'Kod Gönder',
      'Telefonunuza gönderilen kodla yeni şifrenizi belirleyin.': 'Telefonunuza gönderilen kodla yeni şifrenizi belirleyin.',

      // Uyarı ve Değişiklik Mesajları
      'Uyarı': 'Uyarı',
      'Aşağıdaki değişiklikler yapılacak:': 'Aşağıdaki değişiklikler yapılacak:',
      'Email adresi değiştirilecek': 'Email adresi değiştirilecek',
      'Email doğrulama durumu sıfırlanacak': 'Email doğrulama durumu sıfırlanacak',
      'Yeni email için doğrulama gerekli': 'Yeni email için doğrulama gerekli',
      'Telefon numarası değiştirilecek': 'Telefon numarası değiştirilecek',
      'Telefon doğrulama durumu sıfırlanacak': 'Telefon doğrulama durumu sıfırlanacak',
      'Yeni telefon için doğrulama gerekli': 'Yeni telefon için doğrulama gerekli',
      'Devam etmek istiyor musunuz?': 'Devam etmek istiyor musunuz?',
      'İptal': 'İptal',
      'Devam Et': 'Devam Et',
      'Email doğrulama durumu sıfırlandı. Lütfen yeni email adresinizi doğrulayın.': 'Email doğrulama durumu sıfırlandı. Lütfen yeni email adresinizi doğrulayın.',
      'Telefon doğrulama kodu yeni numaranıza gönderildi. Lütfen telefon numaranızı doğrulayın.': 'Telefon doğrulama kodu yeni numaranıza gönderildi. Lütfen telefon numaranızı doğrulayın.',

      // Başarı Mesajları
      'Giriş Başarılı': 'Giriş Başarılı',
      'Başarıyla giriş yaptınız!': 'Başarıyla giriş yaptınız!',
      'Hoş geldiniz!': 'Hoş geldiniz!',
      
      // Satıcı İlgili
      'Satıcı Mağazası': 'Satıcı Mağazası',
      'Mağazaya Git': 'Mağazaya Git',
      'Ürünlerim': 'Ürünlerim',
      'Siparişler': 'Siparişler',
      'Henüz ürün eklenmemiş': 'Henüz ürün eklenmemiş',
      'İlk Ürününü Ekle': 'İlk Ürününü Ekle',
      'Ürünü Düzenle': 'Ürünü Düzenle',
      'Yeni Ürün Ekle': 'Yeni Ürün Ekle',
      'Ürün Adı': 'Ürün Adı',
      'Ürün adı gerekli': 'Ürün adı gerekli',
      'Fiyat': 'Fiyat',
      'Fiyat gerekli': 'Fiyat gerekli',
      'Geçerli bir fiyat girin': 'Geçerli bir fiyat girin',
      'Açıklama': 'Açıklama',
      'Açıklama gerekli': 'Açıklama gerekli',
      'Kategori': 'Kategori',
      'Ürün Fotoğrafı': 'Ürün Fotoğrafı',
      'Fotoğraf Seç': 'Fotoğraf Seç',
      'Değiştir': 'Değiştir',
      'Lütfen bir ürün fotoğrafı seçin': 'Lütfen bir ürün fotoğrafı seçin',
      'Ürün kaydedilirken hata oluştu. Lütfen tekrar deneyin.': 'Ürün kaydedilirken hata oluştu. Lütfen tekrar deneyin.',
      'Düzenle': 'Düzenle',
      'Sil': 'Sil',
      'Güncelle': 'Güncelle',
      'Ekle': 'Ekle',
      'Satıcıları takip etmek için satıcı profillerini ziyaret edin': 'Satıcıları takip etmek için satıcı profillerini ziyaret edin',
      
      // Satıcı Dashboard
      'Hızlı İstatistikler': 'Hızlı İstatistikler',
      'Sipariş Durumları': 'Sipariş Durumları',
      'Aktif Siparişler': 'Aktif Siparişler',
      'Öne Çıkanlar': 'Öne Çıkanlar',
      'Hesap Bilgilerim': 'Hesap Bilgilerim',
      'Değerlendirmeler': 'Değerlendirmeler',
      'Onaylı': 'Onaylı',
      'Satış': 'Satış',
      'Aktif siparişler yüklenirken hata oluştu': 'Aktif siparişler yüklenirken hata oluştu',
      
      // Satıcı Siparişler
      'Teslim Edilen': 'Teslim Edilen',
      'İptal Edilen': 'İptal Edilen',
      'Müşteri Bilgileri': 'Müşteri Bilgileri',
      'Telefon bilgisi yok': 'Telefon bilgisi yok',
      'Bina': 'Bina',
      'Daire': 'Daire',
      'Sipariş Edilen Ürünler': 'Sipariş Edilen Ürünler',
      'Adet': 'Adet',
      'Sipariş Durumu Güncelle': 'Sipariş Durumu Güncelle',
      'Sipariş Alındı': 'Sipariş Alındı',
      'İptal Et': 'İptal Et',
      'Kargoya Verildi': 'Kargoya Verildi',
      'Teslim Edildi': 'Teslim Edildi',
      'Siparişler yüklenirken hata oluştu. Lütfen tekrar deneyin.': 'Siparişler yüklenirken hata oluştu. Lütfen tekrar deneyin.',
      'Sipariş durumu güncellendi': 'Sipariş durumu güncellendi',
      'Sipariş durumu güncellenirken hata oluştu. Lütfen tekrar deneyin.': 'Sipariş durumu güncellenirken hata oluştu. Lütfen tekrar deneyin.',
      
      // Satıcı Değerlendirmeler
      'Henüz değerlendirme yok': 'Henüz değerlendirme yok',
      'yorum': 'yorum',
      'Bu ürün için henüz değerlendirme yok': 'Bu ürün için henüz değerlendirme yok',
      'Anonim': 'Anonim',
      
      // Satıcı Profil Düzenleme
      'Profil Düzenle': 'Profil Düzenle',
      'Logo Seç': 'Logo Seç',
      'Kaldır': 'Kaldır',
      'Mağaza Açıklaması': 'Mağaza Açıklaması',
      'Kargo Şirketi': 'Kargo Şirketi',
      'Kargo şirketi seçiniz': 'Kargo şirketi seçiniz',
      'Profili Güncelle': 'Profili Güncelle',
      'Profil başarıyla güncellendi': 'Profil başarıyla güncellendi',
      'Profil güncellenirken hata oluştu. Lütfen tekrar deneyin.': 'Profil güncellenirken hata oluştu. Lütfen tekrar deneyin.',
      'Logo seçilirken hata oluştu. Lütfen tekrar deneyin.': 'Logo seçilirken hata oluştu. Lütfen tekrar deneyin.',
      
      // Satıcı Giriş
      'Satıcı Girişi': 'Satıcı Girişi',
      
      // Satıcı Profili
      'Satıcı Profili': 'Satıcı Profili',
      'Mağaza Adı': 'Mağaza Adı',
      'Satıcı Adı': 'Satıcı Adı',
      'Kargo': 'Kargo',
      'Ürün': 'Ürün',
      'Mağaza Ürünleri': 'Mağaza Ürünleri',
      'Bu mağazada henüz ürün bulunmuyor': 'Bu mağazada henüz ürün bulunmuyor',
      
      // Hesap Bilgileri
      'Bu sayfayı kullanabilmek için giriş yapmanız gerekmektedir.': 'Bu sayfayı kullanabilmek için giriş yapmanız gerekmektedir.',
      'Kişisel Bilgilerim': 'Kişisel Bilgilerim',
      'Kullanıcı': 'Kullanıcı',
      'Kaydediliyor...': 'Kaydediliyor...',
      'Değişiklikleri Kaydet': 'Değişiklikleri Kaydet',
      'Kullanıcı bilgisi bulunamadı!': 'Kullanıcı bilgisi bulunamadı!',
      'Bilgiler başarıyla güncellendi!': 'Bilgiler başarıyla güncellendi!',
      'Bilgiler güncellenirken hata oluştu. Lütfen tekrar deneyin.': 'Bilgiler güncellenirken hata oluştu. Lütfen tekrar deneyin.',
      
      // Siparişler
      'Sipariş Geçmişi': 'Sipariş Geçmişi',
      'Henüz siparişiniz bulunmuyor': 'Henüz siparişiniz bulunmuyor',
      'Sipariş Detayı': 'Sipariş Detayı',
      'Sipariş Tarihi': 'Sipariş Tarihi',
      'Sipariş Durumu': 'Sipariş Durumu',
      'Toplam Tutar': 'Toplam Tutar',
      'Sipariş Numarası': 'Sipariş Numarası',
      'Beklemede': 'Beklemede',
      'Hazırlanıyor': 'Hazırlanıyor',
      'Kargoda': 'Kargoda',
      'İptal Edildi': 'İptal Edildi',
      
      // Sipariş Durumları
      'Aktif': 'Aktif',
      'Tamamlanan': 'Tamamlanan',
      'İşleme Alındı': 'İşleme Alındı',
      'Bilinmiyor': 'Bilinmiyor',
      'Henüz aktif sipariş yok.': 'Henüz aktif sipariş yok.',
      'Henüz geçmiş sipariş yok.': 'Henüz geçmiş sipariş yok.',
      'Henüz iptal edilen sipariş yok.': 'Henüz iptal edilen sipariş yok.',
      'Sipariş Kodu': 'Sipariş Kodu',
      'Sipariş Verildi': 'Sipariş Verildi',
      'Siparişiniz alındı': 'Siparişiniz alındı',
      'Sipariş': 'Sipariş',
      'Satıcı siparişinizi işleme aldı': 'Satıcı siparişinizi işleme aldı',
      'Siparişiniz kargoya verildi': 'Siparişiniz kargoya verildi',
      'Siparişiniz teslim edildi': 'Siparişiniz teslim edildi',
      'Tahmini Teslim': 'Tahmini Teslim',
      'Ürün  tarihinde teslim edilmiştir': 'Ürün  tarihinde teslim edilmiştir',
      'Ürünler': 'Ürünler',
      
      // Favoriler
      'Favori Ürünlerim': 'Favori Ürünlerim',
      'Henüz favori ürününüz bulunmuyor': 'Henüz favori ürününüz bulunmuyor',
      'Favorilere Ekle': 'Favorilere Ekle',
      'Favorilerden Çıkar': 'Favorilerden Çıkar',
      
      // Adresler
      'Adres Ekle': 'Adres Ekle',
      'Adres Düzenle': 'Adres Düzenle',
      'Adres Sil': 'Adres Sil',
      'Adres Başlığı': 'Adres Başlığı',
      'Adres Detayı': 'Adres Detayı',
      'Şehir': 'Şehir',
      'İlçe': 'İlçe',
      'Posta Kodu': 'Posta Kodu',
      'Varsayılan Adres': 'Varsayılan Adres',
      'Adres başarıyla eklendi': 'Adres başarıyla eklendi',
      'Adres başarıyla güncellendi': 'Adres başarıyla güncellendi',
      'Adres başarıyla silindi': 'Adres başarıyla silindi',
      'Adres eklenirken hata oluştu': 'Adres eklenirken hata oluştu',
      'Adres güncellenirken hata oluştu': 'Adres güncellenirken hata oluştu',
      'Adres silinirken hata oluştu': 'Adres silinirken hata oluştu',
      'Henüz adres eklenmemiş': 'Henüz adres eklenmemiş',
      
      // Ödeme Yöntemleri
      'Kart Ekle': 'Kart Ekle',
      'Kart Düzenle': 'Kart Düzenle',
      'Kart Sil': 'Kart Sil',
      'Kart Numarası': 'Kart Numarası',
      'Kart Sahibi': 'Kart Sahibi',
      'Son Kullanma Tarihi': 'Son Kullanma Tarihi',
      'Varsayılan Kart': 'Varsayılan Kart',
      'Kart başarıyla eklendi': 'Kart başarıyla eklendi',
      'Kart başarıyla güncellendi': 'Kart başarıyla güncellendi',
      'Kart başarıyla silindi': 'Kart başarıyla silindi',
      'Kart eklenirken hata oluştu': 'Kart eklenirken hata oluştu',
      'Kart güncellenirken hata oluştu': 'Kart güncellenirken hata oluştu',
      'Kart silinirken hata oluştu': 'Kart silinirken hata oluştu',
      'Henüz kart eklenmemiş': 'Henüz kart eklenmemiş',
      'Yeni Adres Ekle': 'Yeni Adres Ekle',
      'Yeni Kart Ekle': 'Yeni Kart Ekle',
      
      // Ürün Değerlendirmeleri
      'Ürün Değerlendirmesi': 'Ürün Değerlendirmesi',
      'Ürünü Değerlendir': 'Ürünü Değerlendir',
      'Değerlendirilecek Ürünler': 'Değerlendirilecek Ürünler',
      'Yorumunuz (İsteğe bağlı)': 'Yorumunuz (İsteğe bağlı)',
      'Ürün hakkında düşüncelerinizi paylaşın...': 'Ürün hakkında düşüncelerinizi paylaşın...',
      'Değerlendirmeleri Gönder': 'Değerlendirmeleri Gönder',
      'Lütfen tüm ürünleri değerlendirin': 'Lütfen tüm ürünleri değerlendirin',
      'Değerlendirmeleriniz başarıyla gönderildi': 'Değerlendirmeleriniz başarıyla gönderildi',
      'Değerlendirme gönderilirken hata oluştu': 'Değerlendirme gönderilirken hata oluştu',
      
      // Dialog Mesajları
      'Düzenleme özelliği yakında eklenecek': 'Düzenleme özelliği yakında eklenecek',
      'Favorilerinizi görüntülemek için giriş yapmanız gerekiyor.': 'Favorilerinizi görüntülemek için giriş yapmanız gerekiyor.',
      'Henüz hiç satıcı takip etmiyorsunuz': 'Henüz hiç satıcı takip etmiyorsunuz',

      // Adres Form Alanları
      'Mahalle': 'Mahalle',
      'Sokak': 'Sokak',
      'Bina No': 'Bina No',
      'Daire No': 'Daire No',
      'Adres Adı (Ev, İş vb.)': 'Adres Adı (Ev, İş vb.)',
      'Adresi Kaydet': 'Adresi Kaydet',
      'Şehir zorunludur': 'Şehir zorunludur',
      'İlçe zorunludur': 'İlçe zorunludur',
      'Mahalle zorunludur': 'Mahalle zorunludur',
      'Sokak zorunludur': 'Sokak zorunludur',
      'Bina no zorunludur': 'Bina no zorunludur',
      'Daire no zorunludur': 'Daire no zorunludur',
      'Adres adı zorunludur': 'Adres adı zorunludur',
      'Adres eklenirken hata oluştu. Lütfen bilgilerinizi kontrol edip tekrar deneyin.': 'Adres eklenirken hata oluştu. Lütfen bilgilerinizi kontrol edip tekrar deneyin.',
      
      // Kredi Kartı Form Alanları
      'Kart Adı': 'Kart Adı',
      '1234 5678 9012 3456': '1234 5678 9012 3456',
      'AA/YY': 'AA/YY',
      'Bakiye': 'Bakiye',
      '₺ ': '₺ ',
      'Kartı Kaydet': 'Kartı Kaydet',
      'Kart adı zorunludur': 'Kart adı zorunludur',
      'Kart numarası zorunludur': 'Kart numarası zorunludur',
      'Kart numarası 16 haneli olmalıdır': 'Kart numarası 16 haneli olmalıdır',
      'Son kullanma tarihi zorunludur': 'Son kullanma tarihi zorunludur',
      'AA/YY formatında olmalıdır': 'AA/YY formatında olmalıdır',
      'CVV zorunludur': 'CVV zorunludur',
      'CVV 3 haneli olmalıdır': 'CVV 3 haneli olmalıdır',
      'Bakiye zorunludur': 'Bakiye zorunludur',
      'Geçerli bir bakiye giriniz': 'Geçerli bir bakiye giriniz',
      'Kart eklenirken hata oluştu. Lütfen bilgilerinizi kontrol edip tekrar deneyin.': 'Kart eklenirken hata oluştu. Lütfen bilgilerinizi kontrol edip tekrar deneyin.',
      'منتجات': 'Products',
      'kategorisinde ürün bulunamadı': 'No products found in this category',
      'Profil Ayarları': 'Profile Settings',
      'Hesap bilgilerini düzenle': 'Edit account information',
      'Bildirimler': 'Notifications',
      'Bildirim tercihleri': 'Notification preferences',
      'Tema': 'Theme',
      'Uygulama teması': 'App theme',
      'Güvenlik': 'Security',
      'Şifre ve güvenlik': 'Password and security',
      'Bildirim Ayarları': 'Notification Settings',
      'Sipariş Bildirimleri': 'Order Notifications',
      'Yeni sipariş geldiğinde bildirim al': 'Get notified when new orders arrive',
      'Değerlendirme Bildirimleri': 'Review Notifications',
      'Yeni değerlendirme geldiğinde bildirim al': 'Get notified when new reviews arrive',
      'Tema Ayarları': 'Theme Settings',
      'Sistem Teması': 'System Theme',
      'Telefon ayarlarına uy': 'Follow phone settings',
      'Açık Tema': 'Light Theme',
      'Açık renk teması': 'Light color theme',
      'Koyu Tema': 'Dark Theme',
      'Koyu renk teması': 'Dark color theme',
      'Güvenlik Ayarları': 'Security Settings',
      'Şifre Değiştir': 'Şifre Değiştir',
      'Biometrik Giriş': 'Biometric Login',
      'Mevcut Şifre': 'Mevcut Şifre',
      'Yeni Şifre Tekrar': 'Yeni Şifre (Tekrar)',
      'Tahmini Teslimat': 'Tahmini Teslimat',
      'Ürün bilgilerini güncelleyin': 'Ürün bilgilerini güncelleyin',
      'Mağazanıza yeni ürün ekleyin': 'Mağazanıza yeni ürün ekleyin',
      'Gizlilik şartları': 'Gizlilik şartları',
      'Kullanım koşulları': 'Kullanım koşulları',
      'Gizlilik politikası içeriği burada yer alacak.': 'Gizlilik politikası içeriği burada yer alacak.',
      'Kullanım şartları içeriği burada yer alacak.': 'Kullanım şartları içeriği burada yer alacak.',
      'Giriş yapmak için bir yöntem seçin': 'Giriş yapmak için bir yöntem seçin',
      'Yasal': 'Yasal',
      'Hakkında': 'Hakkında',
      'Teslim Tarihi': 'Teslim Tarihi',
      'Değerlendirildi': 'Değerlendirildi',
      'Kart Sahibinin Adı ve Soyadı': 'Kart Sahibinin Adı ve Soyadı',
      'Kart No': 'Kart No', 
      'Son Kullanma': 'Son Kullanma',
      'Güvenli Ödeme Yöntemi': 'Güvenli Ödeme Yöntemi',
      'Kullanıcı Adı Gizleme': 'Kullanıcı Adı Gizleme',
      'Yorumlarda kullanıcı adınızı gizler': 'Yorumlarda kullanıcı adınızı gizler',   
    },
    'English': {
      // Ana Sayfa
      'Ana Sayfa': 'Home',
      'Hoş Geldiniz': 'Welcome',
      'Ürün ara...': 'Search products...',
      'Tümü': 'All',
      'Kıyafet': 'Clothing',
      'Elektronik': 'Electronics',
      'Kozmetik': 'Cosmetics',
      'Mobilya': 'Furniture',
      'Spor': 'Sports',
      'Oyuncak': 'Toys',
      'Ürün bulunamadı': 'No products found',
      'Keşfet': 'Explore',
      
      // Sepet
      'Sepetim': 'My Cart',
      'Ürünleriniz': 'Your Products',
      'Seçim Yap': 'Select All',
      'Toplam:': 'Total:',
      'Ödemeye Geç': 'Proceed to Payment',
      'Ürün Sepette': 'Product in Cart',
      'Sepete Ekle': 'Add to Cart',
      'Sepetiniz boş': 'Your cart is empty',
      'Giriş Gerekli': 'Login Required',
      'Ödeme işlemi için giriş yapmanız gerekiyor!': 'You need to login to proceed with payment!',
      
      // Profil
      'Profilim': 'My Profile',
      'Hesap Bilgileriniz': 'Your Account Information',
      'Hesap Bilgileri': 'Account Information',
      'Siparişlerim': 'My Orders',
      'Favorilerim': 'My Favorites',
      'Adreslerim': 'My Addresses',
      'Ödeme Yöntemleri': 'Payment Methods',
      'Ayarlar': 'Settings',
      'Çıkış Yap': 'Logout',
      'Kişisel bilgilerinizi yönetin': 'Manage your personal information',
      'Sipariş geçmişinizi görüntüleyin': 'View your order history',
      'Beğendiğiniz ürünleri görüntüleyin': 'View your favorite products',
      'Takip ettiğiniz satıcıları yönetin': 'Manage followed sellers',
      'Kayıtlı adreslerinizi yönetin': 'Manage saved addresses',
      'Kart bilgilerinizi yönetin': 'Manage your card details',
      'Uygulama ayarlarınızı yönetin': 'Manage app settings',
      'Takip Ettiğim Satıcılar': 'Followed Sellers',

      // Ürün Detayı
      'Ürün Detayı': 'Product Detail',
      'Ürün Açıklaması': 'Product Description',
      'Satıcı Bilgileri': 'Seller Information',
      
      // Ayarlar
      'Genel Ayarlar': 'General Settings',
      'Dil': 'Language',
      'Dil Seçimi': 'Language Selection',
      'İptal': 'Cancel',
      'Uygulama Hakkında': 'About App',
      'Versiyon': 'Version',
      'Gizlilik Politikası': 'Privacy Policy',
      'Kullanım Şartları': 'Terms of Use',
      
      // Giriş/Kayıt
      'Giriş Yap': 'Login',
      'Kayıt Ol': 'Sign Up',
      'E-posta': 'Email',
      'Şifre': 'Password',
      'Şifremi Unuttum': 'Forgot Password',
      'Giriş Yap/Kayıt Ol': 'Login/Sign Up',
      'E-posta adresiniz': 'Your email address',
      'Şifreniz': 'Your password',
      'Geçerli bir e-posta adresi giriniz': 'Please enter a valid email address',
      'Şifre en az 6 karakter olmalıdır': 'Password must be at least 6 characters',
      'Lütfen tüm alanları doldurunuz!': 'Please fill in all fields!',
      'E-posta veya şifre hatalı!': 'Email or password is incorrect!',
      'Giriş Başarısız': 'Login Failed',
      'Hesabınız yok mu?': 'Don\'t have an account?',
      'Kayıt Olun': 'Sign Up',
      'Hesabınıza giriş yapın': 'Sign in to your account',
      'Hata': 'Error',
      'Bilgi': 'Information',
      'Tamam': 'OK',
      'Hesap Oluştur': 'Create Account',
      'Bilgilerinizi girerek hesap oluşturun': 'Create an account by entering your details',
      'Ad Soyad': 'Full Name',
      'Ad soyad en az 2 karakter olmalıdır': 'Full name must be at least 2 characters',
      'Telefon': 'Phone',
      'Geçerli bir telefon numarası giriniz': 'Please enter a valid phone number',
      'Şifre Tekrar': 'Confirm Password',
      'Şifreler eşleşmiyor': 'Passwords do not match',
      'Kayıt Başarılı': 'Registration Successful',
      'Hesabınız başarıyla oluşturuldu!': 'Your account has been successfully created!',
      'Zaten hesabınız var mı?': 'Already have an account?',
      'Giriş Yapın': 'Log In',
      
      // Ödeme Sayfası
      'Ödeme': 'Payment',
      'Teslimat Adresi': 'Delivery Address',
      'Kayıtlı adres yok. Lütfen profilinizden adres ekleyin.': 'No saved address. Please add an address from your profile.',
      'Adres': 'Address',
      'Ödeme Kartı': 'Payment Card',
      'Kayıtlı kart yok. Lütfen profilinizden kart ekleyin.': 'No saved card. Please add a card from your profile.',
      'CVV': 'CVV',
      'Sepet Özeti': 'Cart Summary',
      'Ödemeyi Tamamla': 'Complete Payment',
      'Lütfen adres ve kart seçiniz!': 'Please select an address and card!',
      'CVV 3 haneli olmalı!': 'CVV must be 3 digits!',
      'CVV hatalı!': 'CVV is incorrect!',
      'Kart bakiyesi yetersiz!': 'Insufficient card balance!',
      'Ödeme Başarısız': 'Payment Failed',
      'Ödeme işlemi başarısız:': 'Payment process failed:',
      'Para çekilmedi!': 'Money was not withdrawn!',
      
      // Satıcı
      'Satıcı Ol': 'Become a Seller',
      'Satıcı Paneli': 'Seller Panel',
      'Sipariş': 'Order',
      
      // Navigasyon
      'Sepet': 'Cart',
      'Profil': 'Profile',
      
      // Ödeme Başarılı Sayfası
      'Ödeme Başarılı!': 'Payment Successful!',
      'Siparişiniz başarıyla alındı.': 'Your order has been successfully received.',
      'Ana Sayfaya Dön': 'Return to Home',
      
      // Şifre Sıfırlama
      'Şifre Sıfırlama': 'Password Reset',
      'Bilgilerinizi girerek şifrenizi sıfırlayın': 'Enter your information to reset your password',
      'Yeni Şifre': 'New Password',
      'Şifreyi Sıfırla': 'Reset Password',
      'Telefon numarası 11 haneli olmalıdır': 'Phone number must be 11 digits',
      'Şifre en az 8 karakter, bir büyük harf, bir küçük harf ve bir rakam içermelidir': 'Password must be at least 8 characters, one uppercase letter, one lowercase letter and one number',
      'Form Hatası': 'Form Error',
      'Lütfen tüm alanları doğru şekilde doldurunuz!': 'Please fill in all fields correctly!',
      'Geçerli bir e-posta adresi giriniz!': 'Please enter a valid email address!',
      'Şifre en az 8 karakter, bir büyük harf, bir küçük harf ve bir rakam içermelidir!': 'Password must be at least 8 characters, one uppercase letter, one lowercase letter and one number!',
      'Telefon numarası 11 haneli olmalıdır!': 'Phone number must be 11 digits!',
      'Bu telefon numarasına kayıtlı başka bir hesap vardır': 'Another account is registered with this phone number',
      'Bu telefon numarası zaten doğrulanmış': 'This phone number is already verified',
      'Başarılı!': 'Success!',
      'Şifreniz başarıyla değiştirildi. Yeni şifrenizle giriş yapabilirsiniz.': 'Your password has been successfully changed. You can now login with your new password.',
      'Bilgiler eşleşmiyor! Lütfen girdiğiniz bilgileri kontrol edin.': 'Information does not match! Please check the information you entered.',
      'Şifre değiştirme sırasında bir hata oluştu. Lütfen tekrar deneyin.': 'An error occurred while changing the password. Please try again.',
      'Geri dönmek istiyor musunuz? ': 'Do you want to go back? ',
      'Şifreyi Güncelle': 'Update Password',
      'Şifrenizi değiştirdikten sonra yeniden giriş yapmanız gerekir.': 'You need to log in again after changing your password.',
      
      // Kayıt Ol Sayfası
      'Kayıt Başarısız': 'Registration Failed',
      'Bu telefon numarası zaten kullanımda olabilir. Lütfen farklı bir telefon numarası deneyin.': 'This phone number may already be in use. Please try a different phone number.',
      'Email Doğrulama': 'Email Verification',
      'Email doğrulanmış': 'Email verified',
      'Email doğrulanmamış': 'Email not verified',
      'Doğrulama Kodu Gönder': 'Send Verification Code',
      'Gönderiliyor...': 'Sending...',
      'Doğrulama kodu': 'Verification code',
      'Doğrula': 'Verify',
      'Email doğrulama kodu gönderildi!': 'Email verification code sent!',
      'Email adresi başarıyla doğrulandı!': 'Email address successfully verified!',
      'Lütfen doğrulama kodunu girin!': 'Please enter verification code!',
      'Telefon Doğrulama': 'Phone Verification',
      'Telefon doğrulanmış': 'Phone verified',
      'Telefon doğrulanmamış': 'Phone not verified',
      'Telefonu Doğrula': 'Verify Phone',
      'Hesabınız başarıyla oluşturuldu. Şimdi giriş yapabilirsiniz.': 'Your account has been successfully created. You can now login.',
      'Kod Gönder': 'Send message',
      'Telefonunuza gönderilen kodla yeni şifrenizi belirleyin.': 'Set your new password using the code sent to your phone.',

      // Uyarı ve Değişiklik Mesajları
      'Uyarı': 'Warning',
      'Aşağıdaki değişiklikler yapılacak:': 'The following changes will be made:',
      'Email adresi değiştirilecek': 'Email address will be changed',
      'Email doğrulama durumu sıfırlanacak': 'Email verification status will be reset',
      'Yeni email için doğrulama gerekli': 'Verification required for new email',
      'Telefon numarası değiştirilecek': 'Phone number will be changed',
      'Telefon doğrulama durumu sıfırlanacak': 'Phone verification status will be reset',
      'Yeni telefon için doğrulama gerekli': 'Verification required for new phone',
      'Devam etmek istiyor musunuz?': 'Do you want to continue?',
      'İptal': 'Cancel',
      'Devam Et': 'Continue',
      'Email doğrulama durumu sıfırlandı. Lütfen yeni email adresinizi doğrulayın.': 'Email verification status has been reset. Please verify your new email address.',
      'Telefon doğrulama kodu yeni numaranıza gönderildi. Lütfen telefon numaranızı doğrulayın.': 'Phone verification code has been sent to your new number. Please verify your phone number.',
      
      // Başarı Mesajları
      'Giriş Başarılı': 'Login Successful',
      'Başarıyla giriş yaptınız!': 'You have successfully logged in!',
      'Hoş geldiniz!': 'Welcome!',
      
      // Satıcı İlgili
      'Satıcı Mağazası': 'Seller Store',
      'Mağazaya Git': 'Go to Store',
      'Ürünlerim': 'My Products',
      'Siparişler': 'Orders',
      'Henüz ürün eklenmemiş': 'No products added yet',
      'İlk Ürününü Ekle': 'Add Your First Product',
      'Ürünü Düzenle': 'Edit Product',
      'Yeni Ürün Ekle': 'Add New Product',
      'Ürün Adı': 'Product Name',
      'Ürün adı gerekli': 'Product name required',
      'Fiyat': 'Price',
      'Fiyat gerekli': 'Price required',
      'Geçerli bir fiyat girin': 'Enter a valid price',
      'Açıklama': 'Description',
      'Açıklama gerekli': 'Description required',
      'Kategori': 'Category',
      'Ürün Fotoğrafı': 'Product Photo',
      'Fotoğraf Seç': 'Select Photo',
      'Değiştir': 'Change',
      'Lütfen bir ürün fotoğrafı seçin': 'Please select a product photo',
      'Ürün kaydedilirken hata oluştu. Lütfen tekrar deneyin.': 'An error occurred while saving the product. Please try again.',
      'Düzenle': 'Edit',
      'Sil': 'Delete',
      'Güncelle': 'Update',
      'Ekle': 'Add',
      'Satıcıları takip etmek için satıcı profillerini ziyaret edin': 'Visit seller profiles to follow them.',
      
      // Satıcı Dashboard
      'Hızlı İstatistikler': 'Quick Statistics',
      'Sipariş Durumları': 'Order Status',
      'Aktif Siparişler': 'Active Orders',
      'Öne Çıkanlar': 'Highlights',
      'Hesap Bilgilerim': 'My Account Info',
      'Değerlendirmeler': 'Reviews',
      'Onaylı': 'Verified',
      'Satış': 'Sale',
      'Aktif siparişler yüklenirken hata oluştu': 'An error occurred while loading active orders',
      
      // Satıcı Siparişler
      'Teslim Edilen': 'Delivered',
      'İptal Edilen': 'Cancelled',
      'Müşteri Bilgileri': 'Customer Information',
      'Telefon bilgisi yok': 'No phone information',
      'Bina': 'Building',
      'Daire': 'Apartment',
      'Sipariş Edilen Ürünler': 'Ordered Products',
      'Adet': 'Quantity',
      'Sipariş Durumu Güncelle': 'Update Order Status',
      'Sipariş Alındı': 'Order Received',
      'İptal Et': 'Cancel',
      'Kargoya Verildi': 'Shipped',
      'Teslim Edildi': 'Delivered',
      'Siparişler yüklenirken hata oluştu. Lütfen tekrar deneyin.': 'An error occurred while loading orders. Please try again.',
      'Sipariş durumu güncellendi': 'Order status updated',
      'Sipariş durumu güncellenirken hata oluştu. Lütfen tekrar deneyin.': 'An error occurred while updating order status. Please try again.',
      
      // Satıcı Değerlendirmeler
      'Henüz değerlendirme yok': 'No reviews yet',
      'yorum': 'review',
      'Bu ürün için henüz değerlendirme yok': 'No reviews for this product yet',
      'Anonim': 'Anonymous',
      
      // Satıcı Profil Düzenleme
      'Profil Düzenle': 'Edit Profile',
      'Logo Seç': 'Select Logo',
      'Kaldır': 'Remove',
      'Mağaza Açıklaması': 'Store Description',
      'Kargo Şirketi': 'Shipping Company',
      'Kargo şirketi seçiniz': 'Please select a shipping company',
      'Profili Güncelle': 'Update Profile',
      'Profil başarıyla güncellendi': 'Profile updated successfully',
      'Profil güncellenirken hata oluştu. Lütfen tekrar deneyin.': 'An error occurred while updating profile. Please try again.',
      'Logo seçilirken hata oluştu. Lütfen tekrar deneyin.': 'An error occurred while selecting logo. Please try again.',
      
      // Satıcı Giriş
      'Satıcı Girişi': 'Seller Login',
      
      // Satıcı Profili
      'Satıcı Profili': 'Seller Profile',
      'Mağaza Adı': 'Store Name',
      'Satıcı Adı': 'Seller Name',
      'Kargo': 'Shipping',
      'Ürün': 'Product',
      'Mağaza Ürünleri': 'Store Products',
      'Bu mağazada henüz ürün bulunmuyor': 'No products available in this store yet',
      
      // Hesap Bilgileri
      'Bu sayfayı kullanabilmek için giriş yapmanız gerekmektedir.': 'You need to login to use this page.',
      'Bu alanı kullanabilmek için giriş yapmanız gerekmektedir': 'You need to login to use this area',
      'Bu işlemi yapmak için giriş yapmanız gerekiyor!': 'You need to login to perform this action!',
      'Yeni': 'New',
      'Kişisel Bilgilerim': 'My Personal Information',
      'Kullanıcı': 'User',
      'Kaydediliyor...': 'Saving...',
      'Değişiklikleri Kaydet': 'Save Changes',
      'Kullanıcı bilgisi bulunamadı!': 'User information not found!',
      'Bilgiler başarıyla güncellendi!': 'Information updated successfully!',
      'Bilgiler güncellenirken hata oluştu. Lütfen tekrar deneyin.': 'An error occurred while updating information. Please try again.',
      
      // Siparişler
      'Sipariş Geçmişi': 'Order History',
      'Henüz siparişiniz bulunmuyor': 'You don\'t have any orders yet',
      'Sipariş Detayı': 'Order Detail',
      'Sipariş Tarihi': 'Order Date',
      'Sipariş Durumu': 'Order Status',
      'Toplam Tutar': 'Total Amount',
      'Sipariş Numarası': 'Order Number',
      'Beklemede': 'Pending',
      'Hazırlanıyor': 'Preparing',
      'Kargoda': 'In Transit',
      'İptal Edildi': 'Cancelled',
      
      // Sipariş Durumları
      'Aktif': 'Active',
      'Tamamlanan': 'Completed',
      'İşleme Alındı': 'Processing',
      'Bilinmiyor': 'Unknown',
      'Henüz aktif sipariş yok.': 'No active orders yet.',
      'Henüz geçmiş sipariş yok.': 'No completed orders yet.',
      'Henüz iptal edilen sipariş yok.': 'No cancelled orders yet.',
      'Sipariş Kodu': 'Order Code',
      'Sipariş Verildi': 'Order Placed',
      'Siparişiniz alındı': 'Your order has been received',
      'Satıcı siparişinizi işleme aldı': 'Seller has started processing your order',
      'Siparişiniz kargoya verildi': 'Your order has been shipped',
      'Siparişiniz teslim edildi': 'Your order has been delivered',
      'Tahmini Teslim': 'Estimated Delivery',
      'Ürün  tarihinde teslim edilmiştir': 'Product was delivered on ',
      'Ürünler': 'Products',
      
      // Favoriler
      'Favori Ürünlerim': 'My Favorite Products',
      'Henüz favori ürününüz bulunmuyor': 'You don\'t have any favorite products yet',
      'Favorilere Ekle': 'Add to Favorites',
      'Favorilerden Çıkar': 'Remove from Favorites',
      
      // Adresler
      'Adres Ekle': 'Add Address',
      'Adres Düzenle': 'Edit Address',
      'Adres Sil': 'Delete Address',
      'Adres Başlığı': 'Address Title',
      'Adres Detayı': 'Address Detail',
      'Şehir': 'City',
      'İlçe': 'District',
      'Posta Kodu': 'Postal Code',
      'Varsayılan Adres': 'Default Address',
      'Adres başarıyla eklendi': 'Address added successfully',
      'Adres başarıyla güncellendi': 'Address updated successfully',
      'Adres başarıyla silindi': 'Address deleted successfully',
      'Adres eklenirken hata oluştu': 'An error occurred while adding address',
      'Adres güncellenirken hata oluştu': 'An error occurred while updating address',
      'Adres silinirken hata oluştu': 'An error occurred while deleting address',
      'Henüz adres eklenmemiş': 'No addresses added yet',
      
      // Ödeme Yöntemleri
      'Kart Ekle': 'Add Card',
      'Kart Düzenle': 'Edit Card',
      'Kart Sil': 'Delete Card',
      'Kart Numarası': 'Card Number',
      'Kart Sahibi': 'Card Holder',
      'Son Kullanma Tarihi': 'Expiry Date',
      'Varsayılan Kart': 'Default Card',
      'Kart başarıyla eklendi': 'Card added successfully',
      'Kart başarıyla güncellendi': 'Card updated successfully',
      'Kart başarıyla silindi': 'Card deleted successfully',
      'Kart eklenirken hata oluştu': 'An error occurred while adding card',
      'Kart güncellenirken hata oluştu': 'An error occurred while updating card',
      'Kart silinirken hata oluştu': 'An error occurred while deleting card',
      'Henüz kart eklenmemiş': 'No cards added yet',
      'Yeni Adres Ekle': 'Add New Address',
      'Yeni Kart Ekle': 'Add New Card',
      
      // Product Reviews
      'Ürün Değerlendirmesi': 'Product Review',
      'Ürünü Değerlendir': 'Review Product',
      'Değerlendirilecek Ürünler': 'Products to Review',
      'Yorumunuz (İsteğe bağlı)': 'Your Comment (Optional)',
      'Ürün hakkında düşüncelerinizi paylaşın...': 'Share your thoughts about the product...',
      'Değerlendirmeleri Gönder': 'Submit Reviews',
      'Lütfen tüm ürünleri değerlendirin': 'Please rate all products',
      'Değerlendirmeleriniz başarıyla gönderildi': 'Your reviews have been submitted successfully',
      'Değerlendirme gönderilirken hata oluştu': 'An error occurred while submitting the review',
      
      // Dialog Mesajları
      'Düzenleme özelliği yakında eklenecek': 'Edit feature will be added soon',
      'Favorilerinizi görüntülemek için giriş yapmanız gerekiyor.': 'You need to login to view your favorites.',
      'Henüz hiç satıcı takip etmiyorsunuz': "You aren't following any sellers yet.",

      // Adres Form Alanları
      'Mahalle': 'Neighborhood',
      'Sokak': 'Street',
      'Bina No': 'Building No',
      'Daire No': 'Apartment No',
      'Adres Adı (Ev, İş vb.)': 'Address Name (Home, Work, etc.)',
      'Adresi Kaydet': 'Save Address',
      'Şehir zorunludur': 'City is required',
      'İlçe zorunludur': 'District is required',
      'Mahalle zorunludur': 'Neighborhood is required',
      'Sokak zorunludur': 'Street is required',
      'Bina no zorunludur': 'Building number is required',
      'Daire no zorunludur': 'Apartment number is required',
      'Adres adı zorunludur': 'Address name is required',
      'Adres eklenirken hata oluştu. Lütfen bilgilerinizi kontrol edip tekrar deneyin.': 'An error occurred while adding address. Please check your information and try again.',
      
      // Kredi Kartı Form Alanları
      'Kart Adı': 'Card Name',
      '1234 5678 9012 3456': '1234 5678 9012 3456',
      'AA/YY': 'MM/YY',
      'Bakiye': 'Balance',
      '₺ ': '\$ ',
      'Kartı Kaydet': 'Save Card',
      'Kart adı zorunludur': 'Card name is required',
      'Kart numarası zorunludur': 'Card number is required',
      'Kart numarası 16 haneli olmalıdır': 'Card number must be 16 digits',
      'Son kullanma tarihi zorunludur': 'Expiry date is required',
      'AA/YY formatında olmalıdır': 'Must be in MM/YY format',
      'CVV zorunludur': 'CVV is required',
      'CVV 3 haneli olmalıdır': 'CVV must be 3 digits',
      'Bakiye zorunludur': 'Balance is required',
      'Geçerli bir bakiye giriniz': 'Enter a valid balance',
      'Kart eklenirken hata oluştu. Lütfen bilgilerinizi kontrol edip tekrar deneyin.': 'An error occurred while adding card. Please check your information and try again.',
      'منتجات': 'Products',
      'kategorisinde ürün bulunamadı': 'No products found in this category',
      'Profil Ayarları': 'Profile Settings',
      'Hesap bilgilerini düzenle': 'Edit account information',
      'Bildirimler': 'Notifications',
      'Bildirim tercihleri': 'Notification preferences',
      'Tema': 'Theme',
      'Uygulama teması': 'App theme',
      'Güvenlik': 'Security',
      'Şifre ve güvenlik': 'Password and security',
      'Bildirim Ayarları': 'Notification Settings',
      'Sipariş Bildirimleri': 'Order Notifications',
      'Yeni sipariş geldiğinde bildirim al': 'Get notified when new orders arrive',
      'Değerlendirme Bildirimleri': 'Review Notifications',
      'Yeni değerlendirme geldiğinde bildirim al': 'Get notified when new reviews arrive',
      'Tema Ayarları': 'Theme Settings',
      'Sistem Teması': 'System Theme',
      'Telefon ayarlarına uy': 'Follow phone settings',
      'Açık Tema': 'Light Theme',
      'Açık renk teması': 'Light color theme',
      'Koyu Tema': 'Dark Theme',
      'Koyu renk teması': 'Dark color theme',
      'Güvenlik Ayarları': 'Security Settings',
      'Şifre Değiştir': 'Change Password',
      'Biometrik Giriş': 'Biometric Login',
      'Mevcut Şifre': 'Current Password',
      'Yeni Şifre Tekrar': 'Confirm New Password',
      'Durum': 'Status',

      'Ürün Yorumları': 'Product Reviews',
      'Henüz yorum yapılmamış': 'No reviews yet',
      'Satıcı Kaydı': 'Seller Registration',
      'Satıcı Hesabı Oluştur': 'Create Seller Account',
      'Telefon Numarası': 'Phone Number',
      'Şifreler eşleşmiyor!': 'Passwords do not match!',
      'Devam Et': 'Continue',
      'Sipariş #': 'Order #',
      'Kategoriler': 'Categories',
      'Ürün Değerlendirmeleri': 'Product Reviews',
      'Tüm Kategoriler': 'All Categories',
      'Tahmini Teslimat': 'Estimated Delivery',
      'Ürün bilgilerini güncelleyin': 'Update product information',
      'Mağazanıza yeni ürün ekleyin': 'Add new product to your store',
      'Gizlilik şartları': 'Privacy Terms',
      'Kullanım koşulları': 'Terms of Use',
      'Gizlilik politikası içeriği burada yer alacak.': 'Privacy policy content will be here.',
      'Kullanım şartları içeriği burada yer alacak.': 'Terms of use content will be here.',
      'Giriş yapmak için bir yöntem seçin': 'Choose a way to login',
      'Yasal': 'Legal',
      'Hakkında': 'About',
      'Teslim Tarihi': 'Delivery Date',
      'Değerlendirildi': 'Reviewed',
      'Kart Sahibinin Adı ve Soyadı': 'Name and Surname of the Card Holder',
      'Kart No': 'Card Number',
      'Son Kullanma': 'Expiration Date',
      'Güvenli Ödeme Yöntemi': 'Secure Payment Method',
      'Kullanıcı Adı Gizleme': 'Hide Name and Surname',
      'Yorumlarda kullanıcı adınızı gizler': 'Hide your name and surname in comments',
    },
    'العربية': {
      // Ana Sayfa
      'Ana Sayfa': 'الصفحة الرئيسية',
      'Hoş Geldiniz': 'مرحباً بك',
      'Ürün ara...': 'البحث عن المنتجات...',
      'Tümü': 'الكل',
      'Kıyafet': 'ملابس',
      'Elektronik': 'إلكترونيات',
      'Kozmetik': 'مستحضرات تجميل',
      'Mobilya': 'أثاث',
      'Spor': 'رياضة',
      'Oyuncak': 'ألعاب',
      'Ürün bulunamadı': 'لم يتم العثور على منتجات',
      'Keşfet': 'اكتشف',
      
      // Sepet
      'Sepetim': 'سلة التسوق',
      'Ürünleriniz': 'منتجاتك',
      'Seçim Yap': 'اختر الكل',
      'Toplam:': 'المجموع:',
      'Ödemeye Geç': 'المتابعة للدفع',
      'Ürün Sepette': 'المنتج في السلة',
      'Sepete Ekle': 'أضف إلى السلة',
      'Sepetiniz boş': 'سلة التسوق فارغة',
      'Giriş Gerekli': 'تسجيل الدخول مطلوب',
      'Ödeme işlemi için giriş yapmanız gerekiyor!': 'يجب عليك تسجيل الدخول للمتابعة للدفع!',
      
      // Profil
      'Profilim': 'ملفي الشخصي',
      'Hesap Bilgileriniz': 'معلومات حسابك',
      'Hesap Bilgileri': 'معلومات الحساب',
      'Siparişlerim': 'طلباتي',
      'Favorilerim': 'المفضلة',
      'Adreslerim': 'عناويني',
      'Ödeme Yöntemleri': 'طرق الدفع',
      'Ayarlar': 'الإعدادات',
      'Çıkış Yap': 'تسجيل الخروج',
      'Kişisel bilgilerinizi yönetin': 'إدارة معلوماتك الشخصية',
      'Sipariş geçmişinizi görüntüleyin': 'عرض سجل الطلبات',
      'Beğendiğiniz ürünleri görüntüleyin': 'عرض المنتجات المفضلة',
      'Takip ettiğiniz satıcıları yönetin': 'إدارة البائعين الذين تتابعهم',
      'Kayıtlı adreslerinizi yönetin': 'إدارة العناوين المحفوظة',
      'Kart bilgilerinizi yönetin': 'إدارة معلومات البطاقة',
      'Uygulama ayarlarınızı yönetin': 'إدارة إعدادات التطبيق',
      'Takip Ettiğim Satıcılar': 'البائعون المتابعون',
      
      // Ürün Detayı
      'Ürün Detayı': 'تفاصيل المنتج',
      'Ürün Açıklaması': 'وصف المنتج',
      'Satıcı Bilgileri': 'معلومات البائع',
      
      // Ayarlar
      'Genel Ayarlar': 'الإعدادات العامة',
      'Dil': 'اللغة',
      'Dil Seçimi': 'اختيار اللغة',
      'İptal': 'إلغاء',
      'Uygulama Hakkında': 'حول التطبيق',
      'Versiyon': 'الإصدار',
      'Gizlilik Politikası': 'سياسة الخصوصية',
      'Kullanım Şartları': 'شروط الاستخدام',
      
      // Giriş/Kayıt
      'Giriş Yap': 'تسجيل الدخول',
      'Kayıt Ol': 'إنشاء حساب',
      'E-posta': 'البريد الإلكتروني',
      'Şifre': 'كلمة المرور',
      'Şifremi Unuttum': 'نسيت كلمة المرور',
      'Giriş Yap/Kayıt Ol': 'تسجيل الدخول/إنشاء حساب',
      'E-posta adresiniz': 'عنوان بريدك الإلكتروني',
      'Şifreniz': 'كلمة المرور',
      'Geçerli bir e-posta adresi giriniz': 'يرجى إدخال عنوان بريد إلكتروني صحيح',
      'Şifre en az 6 karakter olmalıdır': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      'Lütfen tüm alanları doldurunuz!': 'يرجى ملء جميع الحقول!',
      'E-posta veya şifre hatalı!': 'البريد الإلكتروني أو كلمة المرور غير صحيحة!',
      'Giriş Başarısız': 'فشل تسجيل الدخول',
      'Hesabınız yok mu?': 'ليس لديك حساب؟',
      'Kayıt Olun': 'إنشاء حساب',
      'Hesabınıza giriş yapın': 'تسجيل الدخول إلى حسابك',
      'Hata': 'خطأ',
      'Bilgi': 'معلومات',
      'Tamam': 'موافق',
      'Hesap Oluştur': 'إنشاء حساب',
      'Bilgilerinizi girerek hesap oluşturun': 'إنشاء حساب بإدخال معلوماتك',
      'Ad Soyad': 'الاسم الكامل',
      'Ad soyad en az 2 karakter olmalıdır': 'يجب أن يكون الاسم الكامل حرفين على الأقل',
      'Telefon': 'الهاتف',
      'Geçerli bir telefon numarası giriniz': 'يرجى إدخال رقم هاتف صحيح',
      'Şifre Tekrar': 'تأكيد كلمة المرور',
      'Şifreler eşleşmiyor': 'كلمات المرور غير متطابقة',
      'Kayıt Başarılı': 'تم التسجيل بنجاح',
      'Hesabınız başarıyla oluşturuldu!': 'تم إنشاء حسابك بنجاح!',
      'Zaten hesabınız var mı?': 'لديك حساب بالفعل؟',
      'Giriş Yapın': 'تسجيل الدخول',
      'Kod Gönder': 'ارسل الرمز',
      'Telefonunuza gönderilen kodla yeni şifrenizi belirleyin.': 'قم بتعيين كلمة المرور الجديدة باستخدام الرمز المرسل إلى هاتفك.',
      
      // Ödeme Sayfası
      'Ödeme': 'الدفع',
      'Teslimat Adresi': 'عنوان التوصيل',
      'Kayıtlı adres yok. Lütfen profilinizden adres ekleyin.': 'لا توجد عناوين محفوظة. يرجى إضافة عنوان من ملفك الشخصي.',
      'Adres': 'العنوان',
      'Ödeme Kartı': 'بطاقة الدفع',
      'Kayıtlı kart yok. Lütfen profilinizden kart ekleyin.': 'لا توجد بطاقات محفوظة. يرجى إضافة بطاقة من ملفك الشخصي.',
      'CVV': 'CVV',
      'Sepet Özeti': 'ملخص السلة',
      'Ödemeyi Tamamla': 'إكمال الدفع',
      'Lütfen adres ve kart seçiniz!': 'يرجى اختيار العنوان والبطاقة!',
      'CVV 3 haneli olmalı!': 'يجب أن يكون CVV 3 أرقام!',
      
      // Satıcı Sayfaları
      'Satıcı Girişi': 'تسجيل دخول البائع',
      'Satıcı Kaydı': 'تسجيل البائع',
      'Satıcı Hesabı Oluştur': 'إنشاء حساب بائع',
      'Telefon Numarası': 'رقم الهاتف',
      'Mağaza Adı': 'اسم المتجر',
      'Satıcı Paneli': 'لوحة البائع',
      'Hızlı İstatistikler': 'إحصائيات سريعة',
      'Sipariş Durumları': 'حالات الطلبات',
      'Aktif Siparişler': 'الطلبات النشطة',
      'Öne Çıkanlar': 'المميزات',
      'Hesap Bilgilerim': 'معلومات حسابي',
      'Değerlendirmeler': 'التقييمات',
      'Ürünlerim': 'منتجاتي',
      'Siparişler': 'الطلبات',
      'Profil': 'الملف الشخصي',
      'Ürün Ekle': 'إضافة منتج',
      'Ürün Adı': 'اسم المنتج',
      'Fiyat': 'السعر',
      'Kategori': 'الفئة',
      'Açıklama': 'الوصف',
      'Resim Seç': 'اختيار صورة',
      'Kaydet': 'حفظ',
      'Ürün başarıyla eklendi!': 'تم إضافة المنتج بنجاح!',
      'Ürün başarıyla güncellendi!': 'تم تحديث المنتج بنجاح!',
      'Ürün başarıyla silindi!': 'تم حذف المنتج بنجاح!',
      'Teslim Edilen': 'تم التوصيل',
      'İptal Edilen': 'ملغي',
      'Beklemede': 'في الانتظار',
      'İşleme Alındı': 'قيد المعالجة',
      'Kargoya Verildi': 'تم الشحن',
      'Teslim Edildi': 'تم التوصيل',
      'İptal Edildi': 'ملغي',
      'Müşteri Bilgileri': 'معلومات العميل',
      'Telefon bilgisi yok': 'لا توجد معلومات هاتف',
      'Bina': 'المبنى',
      'Daire': 'الشقة',
      'Sipariş Tarihi': 'تاريخ الطلب',
      'Tahmini Teslimat': 'التوصيل المتوقع',
      'Sipariş Edilen Ürünler': 'المنتجات المطلوبة',
      'Adet': 'الكمية',
      'Sipariş Alındı': 'تم استلام الطلب',
      'İptal Et': 'إلغاء',
      'Henüz değerlendirme yok': 'لا توجد تقييمات بعد',
      'yorum': 'تعليق',
      'Bu ürün için henüz değerlendirme yok': 'لا توجد تقييمات لهذا المنتج بعد',
      'Anonim': 'مجهول',
      'Sipariş #': 'طلب #',
      'Kategoriler': 'الفئات',
      'Ürün Değerlendirmeleri': 'تقييمات المنتج',
      'Tüm Kategoriler': 'جميع الفئات',
      'Ürünler': 'منتجات',
      'منتجات': 'منتجات',
      'kategorisinde ürün bulunamadı': 'لم يتم العثور على منتجات في هذه الفئة',
      'Profil Ayarları': 'إعدادات الملف الشخصي',
      'Hesap bilgilerini düzenle': 'تعديل معلومات الحساب',
      'Bildirimler': 'الإشعارات',
      'Bildirim tercihleri': 'تفضيلات الإشعارات',
      'Tema': 'المظهر',
      'Uygulama teması': 'مظهر التطبيق',
      'Güvenlik': 'الأمان',
      'Şifre ve güvenlik': 'كلمة المرور والأمان',
      'Bildirim Ayarları': 'إعدادات الإشعارات',
      'Sipariş Bildirimleri': 'إشعارات الطلبات',
      'Yeni sipariş geldiğinde bildirim al': 'احصل على إشعار عند وصول طلبات جديدة',
      'Değerlendirme Bildirimleri': 'إشعارات التقييمات',
      'Yeni değerlendirme geldiğinde bildirim al': 'احصل على إشعار عند وصول تقييمات جديدة',
      'Tema Ayarları': 'إعدادات المظهر',
      'Sistem Teması': 'مظهر النظام',
      'Telefon ayarlarına uy': 'اتبع إعدادات الهاتف',
      'Açık Tema': 'المظهر الفاتح',
      'Açık renk teması': 'مظهر الألوان الفاتحة',
      'Koyu Tema': 'المظهر الداكن',
      'Koyu renk teması': 'مظهر الألوان الداكنة',
      'Güvenlik Ayarları': 'إعدادات الأمان',
      'Şifre Değiştir': 'تغيير كلمة المرور',
      'Biometrik Giriş': 'تسجيل الدخول البيومتري',
      'Mevcut Şifre': 'كلمة المرور الحالية',
      'Yeni Şifre': 'كلمة المرور الجديدة',
      'Yeni Şifre Tekrar': 'تأكيد كلمة المرور الجديدة',
      'Değiştir': 'تغيير',
      'Durum': 'الحالة',
      'Ürün bilgilerini güncelleyin': 'تحديث معلومات المنتج',
      'Mağazanıza yeni ürün ekleyin': 'إضافة منتج جديد إلى متجرك',
      'Gizlilik şartları': 'شروط الخصوصية',
      'Kullanım koşulları': 'شروط الاستخدام',
      'Gizlilik politikası içeriği burada yer alacak.': 'سيتم وضع محتوى سياسة الخصوصية هنا.',
      'Kullanım şartları içeriği burada yer alacak.': 'سيتم وضع شروط الاستخدام هنا.',

      'Ürün Yorumları': 'مراجعات المنتج',
      'Henüz yorum yapılmamış': 'لا توجد مراجعات بعد',
      'Form Hatası': 'خطأ في النموذج',
      'Lütfen tüm alanları doğru şekilde doldurunuz!': 'يرجى ملء جميع الحقول بشكل صحيح!',
      'Şifreler eşleşmiyor!': 'كلمات المرور غير متطابقة!',
      'Geçerli bir e-posta adresi giriniz!': 'يرجى إدخال عنوان بريد إلكتروني صحيح!',
      'Şifre en az 8 karakter, bir büyük harf, bir küçük harf ve bir rakam içermelidir!': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل مع حرف كبير واحد وحرف صغير واحد ورقم واحد!',
      'Telefon numarası 11 haneli olmalıdır!': 'يجب أن يكون رقم الهاتف 11 رقم!',
      'Bu telefon numarasına kayıtlı başka bir hesap vardır': 'هناك حساب آخر مسجل بهذا الرقم',
      'Bu telefon numarası zaten doğrulanmış': 'تم التحقق من هذا الرقم بالفعل',
      'Kayıt Başarısız': 'فشل التسجيل',
      'Bu telefon numarası zaten kullanımda olabilir. Lütfen farklı bir telefon numarası deneyin.': 'رقم الهاتف هذا قد يكون مستخدماً بالفعل. يرجى تجربة رقم هاتف مختلف.',
      'Email Doğrulama': 'التحقق من البريد الإلكتروني',
      'Email doğrulanmış': 'تم التحقق من البريد الإلكتروني',
      'Email doğrulanmamış': 'لم يتم التحقق من البريد الإلكتروني',
      'Doğrulama Kodu Gönder': 'إرسال رمز التحقق',
      'Gönderiliyor...': 'جاري الإرسال...',
      'Doğrulama kodu': 'رمز التحقق',
      'Doğrula': 'تحقق',
      'Email doğrulama kodu gönderildi!': 'تم إرسال رمز التحقق من البريد الإلكتروني!',
      'Email adresi başarıyla doğrulandı!': 'تم التحقق من عنوان البريد الإلكتروني بنجاح!',
      'Lütfen doğrulama kodunu girin!': 'يرجى إدخال رمز التحقق!',
      'Telefon Doğrulama': 'التحقق من الهاتف',
      'Telefon doğrulanmış': 'تم التحقق من الهاتف',
      'Telefon doğrulanmamış': 'لم يتم التحقق من الهاتف',
      'Telefonu Doğrula': 'تحقق من الهاتف',
      'Başarılı!': 'نجح!',
      'Hesabınız başarıyla oluşturuldu. Şimdi giriş yapabilirsiniz.': 'تم إنشاء حسابك بنجاح. يمكنك الآن تسجيل الدخول.',
      
      // Uyarı ve Değişiklik Mesajları
      'Uyarı': 'تحذير',
      'Aşağıdaki değişiklikler yapılacak:': 'سيتم إجراء التغييرات التالية:',
      'Email adresi değiştirilecek': 'سيتم تغيير عنوان البريد الإلكتروني',
      'Email doğrulama durumu sıfırlanacak': 'سيتم إعادة تعيين حالة التحقق من البريد الإلكتروني',
      'Yeni email için doğrulama gerekli': 'التحقق مطلوب للبريد الإلكتروني الجديد',
      'Telefon numarası değiştirilecek': 'سيتم تغيير رقم الهاتف',
      'Telefon doğrulama durumu sıfırlanacak': 'سيتم إعادة تعيين حالة التحقق من الهاتف',
      'Yeni telefon için doğrulama gerekli': 'التحقق مطلوب للهاتف الجديد',
      'Devam etmek istiyor musunuz?': 'هل تريد المتابعة؟',
      'İptal': 'إلغاء',
      'Devam Et': 'استمر',
      'Email doğrulama durumu sıfırlandı. Lütfen yeni email adresinizi doğrulayın.': 'تم إعادة تعيين حالة التحقق من البريد الإلكتروني. يرجى التحقق من عنوان بريدك الإلكتروني الجديد.',
      'Telefon doğrulama kodu yeni numaranıza gönderildi. Lütfen telefon numaranızı doğrulayın.': 'تم إرسال رمز التحقق من الهاتف إلى رقمك الجديد. يرجى التحقق من رقم هاتفك.',
      'Devam Et': 'استمر',
      'Telefon numarası 11 haneli olmalıdır': 'يجب أن يكون رقم الهاتف 11 رقم',
      'Mağaza adı en az 2 karakter olmalıdır': 'يجب أن يكون اسم المتجر حرفين على الأقل',
      'Şifre en az 8 karakter, bir büyük harf, bir küçük harf ve bir rakam içermelidir': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل مع حرف كبير واحد وحرف صغير واحد ورقم واحد',

      'CVV hatalı!': 'رمز الأمان غير صحيح!',
      'Kart bakiyesi yetersiz!': 'رصيد البطاقة غير كافي!',
      'Ödeme Başarısız': 'فشل الدفع',
      'Ödeme işlemi başarısız:': 'فشلت عملية الدفع:',
      'Para çekilmedi!': 'لم يتم سحب المال!',
      
      // Satıcı
      'Satıcı Ol': 'كن بائعاً',
      
      // Navigasyon
      'Sepet': 'السلة',
      
      // Ödeme Başarılı Sayfası
      'Ödeme Başarılı!': 'تم الدفع بنجاح!',
      'Siparişiniz başarıyla alındı.': 'تم استلام طلبك بنجاح.',
      'Ana Sayfaya Dön': 'العودة للصفحة الرئيسية',
      
      // Şifre Sıfırlama
      'Şifre Sıfırlama': 'إعادة تعيين كلمة المرور',
      'Bilgilerinizi girerek şifrenizi sıfırlayın': 'أدخل معلوماتك لإعادة تعيين كلمة المرور',
      'Şifreyi Sıfırla': 'إعادة تعيين كلمة المرور',
      'Şifreniz başarıyla değiştirildi. Yeni şifrenizle giriş yapabilirsiniz.': 'تم تغيير كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.',
      'Bilgiler eşleşmiyor! Lütfen girdiğiniz bilgileri kontrol edin.': 'المعلومات غير متطابقة! يرجى التحقق من المعلومات التي أدخلتها.',
      'Şifre değiştirme sırasında bir hata oluştu. Lütfen tekrar deneyin.': 'حدث خطأ أثناء تغيير كلمة المرور. يرجى المحاولة مرة أخرى.',
      'Geri dönmek istiyor musunuz? ': 'هل تريد العودة؟ ',
      'Şifreyi Güncelle': 'حفظ كلمة السر',
      'Şifrenizi değiştirdikten sonra yeniden giriş yapmanız gerekir.': 'يجب تسجيل الدخول مرة أخرى بعد تغيير كلمة المرور.',

      // Başarı Mesajları
      'Giriş Başarılı': 'تم تسجيل الدخول بنجاح',
      'Başarıyla giriş yaptınız!': 'لقد سجلت الدخول بنجاح!',
      'Hoş geldiniz!': 'مرحباً بك!',
      
      // Satıcı İlgili
      'Satıcı Mağazası': 'متجر البائع',
      'Mağazaya Git': 'اذهب إلى المتجر',
      'Henüz ürün eklenmemiş': 'لم يتم إضافة منتجات بعد',
      'İlk Ürününü Ekle': 'أضف أول منتج لك',
      'Ürünü Düzenle': 'تعديل المنتج',
      'Yeni Ürün Ekle': 'إضافة منتج جديد',
      'Ürün adı gerekli': 'اسم المنتج مطلوب',
      'Fiyat gerekli': 'السعر مطلوب',
      'Geçerli bir fiyat girin': 'أدخل سعراً صحيحاً',
      'Açıklama gerekli': 'الوصف مطلوب',
      'Ürün Fotoğrafı': 'صورة المنتج',
      'Fotoğraf Seç': 'اختر صورة',
      'Lütfen bir ürün fotoğrafı seçin': 'يرجى اختيار صورة للمنتج',
      'Ürün kaydedilirken hata oluştu. Lütfen tekrar deneyin.': 'حدث خطأ أثناء حفظ المنتج. يرجى المحاولة مرة أخرى.',
      'Düzenle': 'تعديل',
      'Sil': 'حذف',
      'Güncelle': 'تحديث',
      'Ekle': 'إضافة',
      'Satıcıları takip etmek için satıcı profillerini ziyaret edin': 'قم بزيارة متاجر البائعين لمتابعتهم.',
      
      // Satıcı Dashboard
      'Onaylı': 'موافق عليه',
      'Satış': 'بيع',
      'Aktif siparişler yüklenirken hata oluştu': 'حدث خطأ أثناء تحميل الطلبات النشطة',
      
      // Satıcı Siparişler
      'Siparişler yüklenirken hata oluştu. Lütfen tekrar deneyin.': 'حدث خطأ أثناء تحميل الطلبات. يرجى المحاولة مرة أخرى.',
      'Sipariş durumu güncellendi': 'تم تحديث حالة الطلب',
      'Sipariş durumu güncellenirken hata oluştu. Lütfen tekrar deneyin.': 'حدث خطأ أثناء تحديث حالة الطلب. يرجى المحاولة مرة أخرى.',

      // Satıcı Profil Düzenleme
      'Profil Düzenle': 'تعديل الملف الشخصي',
      'Logo Seç': 'اختر الشعار',
      'Kaldır': 'إزالة',
      'Mağaza Açıklaması': 'وصف المتجر',
      'Kargo Şirketi': 'شركة الشحن',
      'Kargo şirketi seçiniz': 'يرجى اختيار شركة شحن',
      'Profili Güncelle': 'تحديث الملف الشخصي',
      'Profil başarıyla güncellendi': 'تم تحديث الملف الشخصي بنجاح',
      'Profil güncellenirken hata oluştu. Lütfen tekrar deneyin.': 'حدث خطأ أثناء تحديث الملف الشخصي. يرجى المحاولة مرة أخرى.',
      'Logo seçilirken hata oluştu. Lütfen tekrar deneyin.': 'حدث خطأ أثناء اختيار الشعار. يرجى المحاولة مرة أخرى.',
      
      // Satıcı Profili
      'Satıcı Profili': 'ملف البائع',
      'Satıcı Adı': 'اسم البائع',
      'Kargo': 'الشحن',
      'Ürün': 'المنتج',
      'Mağaza Ürünleri': 'منتجات المتجر',
      'Bu mağazada henüz ürün bulunmuyor': 'لا توجد منتجات في هذا المتجر بعد',
      
      // Hesap Bilgileri
      'Bu sayfayı kullanabilmek için giriş yapmanız gerekmektedir.': 'يجب عليك تسجيل الدخول لاستخدام هذه الصفحة.',
      'Bu alanı kullanabilmek için giriş yapmanız gerekmektedir': 'يجب عليك تسجيل الدخول لاستخدام هذه المنطقة',
      'Bu işlemi yapmak için giriş yapmanız gerekiyor!': 'يجب عليك تسجيل الدخول لتنفيذ هذا الإجراء!',
      'Yeni': 'جديد',
      'Kişisel Bilgilerim': 'معلوماتي الشخصية',
      'Kullanıcı': 'المستخدم',
      'Kaydediliyor...': 'جاري الحفظ...',
      'Değişiklikleri Kaydet': 'حفظ التغييرات',
      'Kullanıcı bilgisi bulunamadı!': 'لم يتم العثور على معلومات المستخدم!',
      'Bilgiler başarıyla güncellendi!': 'تم تحديث المعلومات بنجاح!',
      'Bilgiler güncellenirken hata oluştu. Lütfen tekrar deneyin.': 'حدث خطأ أثناء تحديث المعلومات. يرجى المحاولة مرة أخرى.',
      
      // Siparişler
      'Sipariş Geçmişi': 'سجل الطلبات',
      'Henüz siparişiniz bulunmuyor': 'ليس لديك أي طلبات بعد',
      'Sipariş Detayı': 'تفاصيل الطلب',
      'Sipariş': 'الطلب',
      'Sipariş Durumu': 'حالة الطلب',
      'Toplam Tutar': 'المبلغ الإجمالي',
      'Sipariş Numarası': 'رقم الطلب',
      'Hazırlanıyor': 'قيد التحضير',
      'Kargoda': 'قيد الشحن',
      
      // Sipariş Durumları
      'Aktif': 'نشط',
      'Tamamlanan': 'مكتمل',
      'Bilinmiyor': 'غير معروف',
      'Henüz aktif sipariş yok.': 'لا توجد طلبات نشطة بعد.',
      'Henüz geçmiş sipariş yok.': 'لا توجد طلبات مكتملة بعد.',
      'Henüz iptal edilen sipariş yok.': 'لا توجد طلبات ملغية بعد.',
      'Sipariş Kodu': 'رمز الطلب',
      'Sipariş Verildi': 'تم تقديم الطلب',
      'Siparişiniz alındı': 'تم استلام طلبك',
      'Satıcı siparişinizi işleme aldı': 'بدأ البائع في معالجة طلبك',
      'Siparişiniz kargoya verildi': 'تم شحن طلبك',
      'Siparişiniz teslim edildi': 'تم توصيل طلبك',
      'Tahmini Teslim': 'التوصيل المتوقع',
      'Ürün  tarihinde teslim edilmiştir': 'تم توصيل المنتج في ',
      
      // Favoriler
      'Favori Ürünlerim': 'منتجاتي المفضلة',
      'Henüz favori ürününüz bulunmuyor': 'ليس لديك منتجات مفضلة بعد',
      'Favorilere Ekle': 'إضافة إلى المفضلة',
      'Favorilerden Çıkar': 'إزالة من المفضلة',
      
      // Adresler
      'Adres Ekle': 'إضافة عنوان',
      'Adres Düzenle': 'تعديل العنوان',
      'Adres Sil': 'حذف العنوان',
      'Adres Başlığı': 'عنوان العنوان',
      'Adres Detayı': 'تفاصيل العنوان',
      'Şehir': 'المدينة',
      'İlçe': 'الحي',
      'Posta Kodu': 'الرمز البريدي',
      'Varsayılan Adres': 'العنوان الافتراضي',
      'Adres başarıyla eklendi': 'تم إضافة العنوان بنجاح',
      'Adres başarıyla güncellendi': 'تم تحديث العنوان بنجاح',
      'Adres başarıyla silindi': 'تم حذف العنوان بنجاح',
      'Adres eklenirken hata oluştu': 'حدث خطأ أثناء إضافة العنوان',
      'Adres güncellenirken hata oluştu': 'حدث خطأ أثناء تحديث العنوان',
      'Adres silinirken hata oluştu': 'حدث خطأ أثناء حذف العنوان',
      'Henüz adres eklenmemiş': 'لم يتم إضافة عناوين بعد',
      
      // Ödeme Yöntemleri
      'Kart Ekle': 'إضافة بطاقة',
      'Kart Düzenle': 'تعديل البطاقة',
      'Kart Sil': 'حذف البطاقة',
      'Kart Numarası': 'رقم البطاقة',
      'Kart Sahibi': 'صاحب البطاقة',
      'Son Kullanma Tarihi': 'تاريخ انتهاء الصلاحية',
      'Varsayılan Kart': 'البطاقة الافتراضية',
      'Kart başarıyla eklendi': 'تم إضافة البطاقة بنجاح',
      'Kart başarıyla güncellendi': 'تم تحديث البطاقة بنجاح',
      'Kart başarıyla silindi': 'تم حذف البطاقة بنجاح',
      'Kart eklenirken hata oluştu': 'حدث خطأ أثناء إضافة البطاقة',
      'Kart güncellenirken hata oluştu': 'حدث خطأ أثناء تحديث البطاقة',
      'Kart silinirken hata oluştu': 'حدث خطأ أثناء حذف البطاقة',
      'Henüz kart eklenmemiş': 'لم يتم إضافة بطاقات بعد',
      'Yeni Adres Ekle': 'إضافة عنوان جديد',
      'Yeni Kart Ekle': 'إضافة بطاقة جديدة',
      
      // تقييم المنتجات
      'Ürün Değerlendirmesi': 'تقييم المنتج',
      'Ürünü Değerlendir': 'قيّم المنتج',
      'Değerlendirilecek Ürünler': 'المنتجات المراد تقييمها',
      'Yorumunuz (İsteğe bağlı)': 'تعليقك (اختياري)',
      'Ürün hakkında düşüncelerinizi paylaşين...': 'شارك أفكارك حول المنتج...',
      'Değerlendirmeleri Gönder': 'إرسال التقييمات',
      'Lütfen tüm ürünleri değerlendirin': 'يرجى تقييم جميع المنتجات',
      'Değerlendirmeleriniz başarıyla gönderildi': 'تم إرسال تقييماتك بنجاح',
      'Değerlendirme gönderilirken hata oluştu': 'حدث خطأ أثناء إرسال التقييم',
      
      // Dialog Mesajları
      'Düzenleme özelliği yakında eklenecek': 'ستتم إضافة ميزة التعديل قريباً',
      'Favorilerinizi görüntülemek için giriş yapmanız gerekiyor.': 'يجب عليك تسجيل الدخول لعرض المفضلة.',
      'Henüz hiç satıcı takip etmiyorsunuz': 'أنت لا تتابع أي بائعين بعد.',

      // Adres Form Alanları
      'Mahalle': 'الحي',
      'Sokak': 'الشارع',
      'Bina No': 'رقم المبنى',
      'Daire No': 'رقم الشقة',
      'Adres Adı (Ev, İş vb.)': 'اسم العنوان (المنزل، العمل، إلخ)',
      'Adresi Kaydet': 'حفظ العنوان',
      'Şehir zorunludur': 'المدينة مطلوبة',
      'İlçe zorunludur': 'الحي مطلوب',
      'Mahalle zorunludur': 'الحي مطلوب',
      'Sokak zorunludur': 'الشارع مطلوب',
      'Bina no zorunludur': 'رقم المبنى مطلوب',
      'Daire no zorunludur': 'رقم الشقة مطلوب',
      'Adres adı zorunludur': 'اسم العنوان مطلوب',
      'Adres eklenirken hata oluştu. Lütfen bilgilerinizi kontrol edip tekrar deneyin.': 'حدث خطأ أثناء إضافة العنوان. يرجى التحقق من معلوماتك والمحاولة مرة أخرى.',
      
      // Kredi Kartı Form Alanları
      'Kart Adı': 'اسم البطاقة',
      '1234 5678 9012 3456': '1234 5678 9012 3456',
      'AA/YY': 'ش/س',
      'Bakiye': 'الرصيد',
      '₺ ': 'ر.ت ',
      'Kartı Kaydet': 'حفظ البطاقة',
      'Kart adı zorunludur': 'اسم البطاقة مطلوب',
      'Kart numarası zorunludur': 'رقم البطاقة مطلوب',
      'Kart numarası 16 haneli olmalıdır': 'رقم البطاقة يجب أن يكون 16 رقم',
      'Son kullanma tarihi zorunludur': 'تاريخ انتهاء الصلاحية مطلوب',
      'AA/YY formatında olmalıdır': 'يجب أن يكون بتنسيق ش/س',
      'CVV zorunludur': 'CVV مطلوب',
      'CVV 3 haneli olmalıdır': 'CVV يجب أن يكون 3 أرقام',
      'Bakiye zorunludur': 'الرصيد مطلوب',
      'Geçerli bir bakiye giriniz': 'أدخل رصيداً صحيحاً',
      'Kart eklenirken hata oluştu. Lütfen bilgilerinizi kontrol edip tekrar deneyin.': 'حدث خطأ أثناء إضافة البطاقة. يرجى التحقق من معلوماتك والمحاولة مرة أخرى.',
      'Giriş yapmak için bir yöntem seçin': 'اختر طريقة لتسجيل الدخول',
      'Yasal': 'قانوني',
      'Hakkında': 'حول',
      'Teslim Tarihi': 'تاريخ التسليم',
      'Değerlendirildi': 'تمت مراجعته',
      'Kart Sahibinin Adı ve Soyadı': 'الاسم الكامل لصاحب البطاقة',
      'Kart No': 'رقم البطاقة',
      'Son Kullanma': 'تاريخ الانتهاء',
      'Güvenli Ödeme Yöntemi': 'طريقة الدفع الآمنة',
      'Ürün hakkında düşüncelerinizi paylaşın...': 'شارك أفكارك حول المنتج...',
      'Kullanıcı Adı Gizleme': 'إخفاء اسم المستخدم',
      'Yorumlarda kullanıcı adınızı gizler': 'إخفاء الاسم الكامل في التعليقات',
    },
  };

  static String _currentLanguage = _defaultLanguage;
  static List<Function()> _listeners = [];

  static String get currentLanguage => _currentLanguage;
  
  // Dil değişikliklerini dinlemek için listener ekleme
  static void addListener(Function() listener) {
    _listeners.add(listener);
  }
  
  // Listener'ı kaldırma
  static void removeListener(Function() listener) {
    _listeners.remove(listener);
  }

  static Future<void> initialize() async {
    final prefs = await SharedPreferences.getInstance();
    String? savedLanguage = prefs.getString(_languageKey);
    
    // Eğer kaydedilmiş dil yoksa, telefon dilini algıla
    if (savedLanguage == null) {
      savedLanguage = _detectDeviceLanguage();
    }
    
    _currentLanguage = savedLanguage;
  }

  // Telefon dilini algılama fonksiyonu
  static String _detectDeviceLanguage() {
    final deviceLocale = ui.window.locale;
    final languageCode = deviceLocale.languageCode.toLowerCase();
    
    // Desteklenen dilleri kontrol et
    if (_supportedLanguages.containsKey(languageCode)) {
      return _supportedLanguages[languageCode]!;
    }
    
    // Türkçe ve Arapça dışındaki diller için İngilizce varsayılan
    return 'English';
  }

  static Future<void> setLanguage(String language) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, language);
    _currentLanguage = language;
    
    // Tüm listener'ları bilgilendir
    for (var listener in _listeners) {
      listener();
    }
  }

  static String translate(String key) {
    final translations = _translations[_currentLanguage];
    return translations?[key] ?? key;
  }

  static List<String> get availableLanguages => ['English', 'Türkçe', 'العربية'];
  
  // Dil kodunu döndüren fonksiyon
  static String getLanguageCode(String languageName) {
    for (var entry in _supportedLanguages.entries) {
      if (entry.value == languageName) {
        return entry.key;
      }
    }
    return 'English'; // Varsayılan olarak İngilizce
  }
  
  // Mevcut dil kodunu döndüren fonksiyon
  static String get currentLanguageCode => getLanguageCode(_currentLanguage);
}
